--USER AND WALLETS DOMAIN

CREATE TABLE users(
id SERIAL PRIMARY KEY,
username VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE wallets(
id SERIAL PRIMARY KEY,
user_id INT NOT NULL UNIQUE REFERENCES users(id),
available_balance NUMERIC(6,2) NOT NULL DEFAULT 0,
reserved_balance NUMERIC(6,2) NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE wallet_transactions(
id SERIAL PRIMARY KEY,
wallet_id INT NOT NULL REFERENCES wallets(id),
amount NUMERIC(12,2) NOT NULL,
transaction_type VARCHAR(50) NOT NULL,
ref_type VARCHAR(50),
ref_id INT,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
--USER AND WALLETS DOMAIN
