--USER AND WALLETS DOMAIN

CREATE TABLE users(
id SERIAL PRIMARY KEY,
username VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE wallets(
id SERIAL PRIMARY KEY,
user_id INT NOT NULL UNIQUE REFERENCES users(id),
available_balance NUMERIC(6,2) NOT NULL DEFAULT 0,
reserved_balance NUMERIC(6,2) NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE wallet_transactions(
id SERIAL PRIMARY KEY,
wallet_id INT NOT NULL REFERENCES wallets(id),
amount NUMERIC(12,2) NOT NULL,
transaction_type VARCHAR(50) NOT NULL,
ref_type VARCHAR(50),
ref_id INT,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
--USER AND WALLETS DOMAIN

--EVENTS/MARKETS DOMAIN
CREATE TABLE events(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
start_time TIMESTAMP NOT NULL,
status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE markets(
id SERIAL PRIMARY KEY,
event_id INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE outcomes(
id SERIAL PRIMARY KEY,
market_id INT NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
name VARCHAR(100) NOT NULL,--eg. 'Home', 'Draw', 'Away', 'Over 2.5'
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
--EVENTS/MARKETS DOMAIN

--OFFERS & ORDER BOOK DOMAIN
CREATE TABLE offers(
id SERIAL PRIMARY KEY,
user_id INT NOT NULL REFERENCES users(id),
outcome_id INT NOT NULL REFERENCES outcomes(id),
odds NUMERIC(6,2) NOT NULL,
initial_stake NUMERIC(6,2) NOT NULL,
remaining_stake NUMERIC(6,2) NOT NULL,
status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
    
);
--OFFERS & ORDER BOOK DOMAIN

--MATCHING DOMAIN
CREATE TABLE matches(
id SERIAL PRIMARY KEY,
offer_id INT NOT NULL REFERENCES offers(id),
maker_user_id INT NOT NULL REFERENCES users(id),
taker_user_id INT NOT NULL REFERENCES users(id),
matched_stake NUMERIC(6,2) NOT NULL,
odds NUMERIC(6,2) NOT NULL,--value of the odds at the time of match
created_at TIMESTAMP DEFAULT NOW()
);
--MATCHING DOMAIN